### ISSUE TITLE
Multiple device requests for each device

### ISSUE THREAD

**Issue by Locutus73** [ilcato/homebridge-melcloud#4]
Hi,
This is a follow up to the issue #3.
The error interception works as a workaround, homebridge stopped crashing, but the underlying problem is still persistent.
I have 6 AC units in my setup and, every time I open the home app, I see 30 requests to https://app.melcloud.com/Mitsubishi.Wifi.Client/Device/Get, 5 for each unit; the first 28 get a response from the melcloud server (I can see the json in the homebridge-melcloud output), while the last 2 get the error that is intercepted. The whole process is really slow (home app remains in a “updating” state for 20 seconds, until the last two error responses) and the data fetched in the last two requests in missing (i.e. I see some units reporting 0 degrees Celsius).
I think the problem consists in homebridge-melcloud asking the whole device/unit status for each of the 5 parameters of each device/unit (temperature, operating mode, horizontal tilt, vertical tilt, fan speed) instead of making a single request and caching the result for the subsequent interrogations made in the next seconds; maybe melcloud servers previously tolerated this request flood, and now they respond with an error after 28 requests.

Many thanks in advance.
Best regards

Locutus73

**Comment by ilcato** [comment]
I'm implementing a better access strategy to the MELCloud server. Be patient.

**Comment by ilcato** [comment]
@Locutus73, can you test the latest commit on index.js?

**Comment by Locutus73** [comment]
Hi,
I just tested the last index.js (commit 0c50ff4).
The logs now are more compact: I get “`[Melcloud] <DeviceName>`” when the plugin tries a device update and “`[Melcloud] There was a problem getting info from: …`” from updates gone bad.
Usually, at first attempt getting status with Home app, I can see 5 rapid successful device updates, the attempt for the 6th device update, then I must wait 20 seconds with the “updating” label in Home app and then I get an error log for the last device update; at this point Home app reports correct data for the first 5 devices and something wrong (i.e. 0 degrees Celsius) for the last one. Now, if I immediately close and open again Home app, I see only a successful device update for the last device (the one that went wrong in the previous attempt) and all the process is rapid and successful (Home app with the “updating” label for few istants). If I wait for some time I get the problem again. Briefly I get the problem when homebridge-melcloud tries to update more than 5 units.

Trying to analyse the behaviour from outside, it seems to me that you are buffering updates in a queue, that fails if there are more than N (I think 28) requests. I don’t want to be intrusive, I beg your pardon in advance, but I think that you should try to consolidate the 5 updates for a single unit (temperature, mode, vert. tilt, horiz. tilt, fan speed) in a single request.

Please tell me if I can help you more than just trying your submits (I’m not expert in NodeJS, but I’m a coder).

Thank you very much again in advance
Best regards
Locutus73

**Comment by ilcato** [comment]
This, is what I'm trying to do. The problem is that I currently have only one unit in my setup :-)

**Comment by ilcato** [comment]
@Locutus73, I implemented a throttling mechanism that allows a maximum of N connections sent in parallel to Melcloud service. In the current version N is 2, because I made same testing and it seems that with a number of requests > 2 the responses are sometimes with an internal server error result.
Can you test it?

**Comment by ilcato** [comment]
@Locutus73 any feedback?

**Comment by Locutus73** [comment]
Hi,
excuse me for the delay, I was busy.
Most of time homebridge-melcloud seems to work fine with the last release, but I still get random “device not responding” or hangs (I mean 20 seconds delay and timeout). Unfortunately, I didn’t find a repeatable pattern, so I’m trying to get more data in order to give you an analytic feedback.
So far, I observed two behaviours:

1. homebridge-melcloud seems to be more reliable when interrogated from a domestic hub (an AppleTV inside the house; the original interrogation made from my iPhone outside the home network) instead of directly interrogated by my iPhone inside the house
2. when I change a parameter of a unit (this is a problem we can investigate in a new GitHub issue), homebridge-melcloud correctly sets the parameter in the melcloud infrastructure, but still reports the old value; this is just cosmetic when I modify the parameter from the Home app, but, when I, for instance, try to switch off heating of the entire home from Siri, Siri reports (wrongly) that six units appears to not respond.

Thank you again,
I’ll report back when I’ll get more consistent observations.

Best regards
Locutus73

**Comment by ilcato** [comment]
@Locutus73, I set the throttling param to 1 so only 1 request at a time is sent to Melcloud. The reason why through the AppleTV you are experiencing a better result is probably because the requests to homebridge are coming slowly.
Try now please.

**Comment by Locutus73** [comment]
Hi,
I have to tell the truth: I’m still testing the index.js with the throttling parameter set to 2, and in the last week it worked flawlessly. Melcloud servers seem to be very temperamental.
Why don’t you make the throttling value and the timeout value optional config.json parameters with conservative default values?

Thank you in advance.
Best regards.

Locutus73

**Comment by ilcato** [comment]
@Locutus73, is this version also addressing issue #2 ?
